# Creates RSA Public/Private Key Pair
# Keypair will be used for AWS infrastructure
- name: generate SSH key
  hosts: 127.0.0.1
  connection: local

  vars:
    ssh_key_filename: aws_key_box

  tasks:

    - name: generate SSH key "{{ssh_key_filename}}"
      openssh_keypair:
        path: "../shared/keys/{{ssh_key_filename}}"
        type: rsa
        size: 4096
        state: present
        force: no