- name: generate INVENTORY.MD
  hosts: 127.0.0.1
  connection: local

  vars_files:
    - "../vars/ansible_vars.yml"
  tasks:
    - include_vars: "{{config_root}}/{{config_vars_file}}"

    - name: Render INVENTORY.md
      template:
        src: templates/INVENTORY.md.j2
        dest: "{{inventory_root}}/INVENTORY.md"
        owner: ubuntu
        group: operator
        mode: 0770      