- name: Load vars
  hosts: platform_api
  vars_files:
   - "../vars/ansible_vars.yml"

  tasks:
    - include_vars: "{{config_root}}/{{config_vars_file}}"
    - debug: msg="solace_spa_user {{solace_spa_user}}"

- name: Install and start platform_api
  hosts: platform_api
  roles:
    - platform-api #deploys and executes docker-compose of platform api
  vars_files:
   - "../vars/ansible_vars.yml"

  tasks:
    - include_vars: "{{config_root}}/{{config_vars_file}}"

    - debug: msg="[config_root/config_vars_filevi  {{config_root}}/{{config_vars_file}}]]"
      when: check_result.stat.exists

    - name: copy
      copy:
        src: files/check_platform_api.sh
        dest: /data/platform-api/docker
        owner: root
        group: root
        mode: 0744
      become: yes

    - name: execute script to check platform-api status
      script: files/check_platform_api.sh /data/platform-api/docker platform-api-server-2
      become: yes

    - name: check server status 
      stat: 
        path: /data/platform-api/docker/tmp/SERVER_INITIALIZED
      register: check_result

    - debug: msg="PLATFORM-API successfully initialized, up and running"
      when: check_result.stat.exists

    - debug: msg="PLATFORM-API NOT UP AND / OR INITIALIZED"
      when: not check_result.stat.exists


