# Registers IP withcloud.mongodb
- name: Register IP with cloud.mongodb
  hosts: 127.0.0.1
  vars_files:
    - "../vars/ansible_vars.yml"

  tasks:
    - include_vars: "{{config_root}}/{{config_vars_file}}"
    - include_vars: "{{generated_infrastructure_vars_file}}"
    - name: Register IP with cloud.mongdo
      uri:
        url: "{{ mongodb_cloud_api_url }}"
        method: POST
        body_format: json
        user: "{{mongodb_cloud_api_user}}"
        password: "{{mongodb_cloud_api_password}}"
        body: '[{"ipAddress" : "{{platform_api_host_ip}}","comment" : "{{ platform_api_comment }}"}]'
        status_code: 201