# Registers IP withcloud.mongodb
- name: Register IP with cloud.mongodb
  hosts: 127.0.0.1
  vars_files:
    - ../vars/sensitive_ansible_vars.yml
    - ../generated/ansible_infrastructure_vars.yml

  tasks:
    - name: Register IP with cloud.mongdo
      uri:
        url: "{{ mongodb_cloud_api_url }}"
        method: POST
        body_format: json
        user: "{{mongodb_cloud_api_user}}"
        password: "{{mongodb_cloud_api_password}}"
        body: '[{"ipAddress" : "{{platform_api_host_ip}}","comment" : "{{ platform_api_comment }}"}]'
        status_code: 201