# Registers IP withcloud.mongodb
- name: Remove IP with cloud.mongodb
  hosts: 127.0.0.1
  vars_files:
    - "../vars/ansible_vars.yml"

  tasks:
    - include_vars: "{{config_root}}/{{config_vars_file}}"
    - include_vars: "{{generated_infrastructure_vars_file}}"
    - name: Remove IP with cloud.mongdo
      uri:
        url: "{{ mongodb_cloud_api_url }}/{{ platform_api_host_ip }}"
        method: DELETE
        body_format: json
        user: "{{mongodb_cloud_api_user}}"
        password: "{{mongodb_cloud_api_password}}"
        status_code: 204